spring.application.name=Eureka-Server

server.port=8855

# Should not register itself with Eureka server as client
eureka.client.register-with-eureka=false
# Should not fetch registry information from Eureka server
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=false
eureka.client.service-url.defaultZone=http://localhost:8855/eureka/